#-------------------------------
# General Site Settings
title: Duc Manh IT Blogs - ROR developer
logo: logo.svg # You can add own logo.
favicon: logo.svg
description: Code is my life


#-------------------------------
# Author Settings
author:
  name: Manh Duc Le
  image: 01.jpg
  say-hello: Hello, I’m <strong>Manh Le Duc</strong>
  bio: Mình là một Web developer mới nhú, cụ thể là mình code Ruby on Rails, ReactJS. Sau một thời gian đi làm culy, thì mình cũng tích lũy được một số kiến thức muốn chia sẽ với mọi người.
  ok: Designs, talks, and writes about <strong>web</strong>, <strong>ethics</strong>, <strong>privacy</strong>, and dev. I share design tutorials, free resources and inspiration. Loves <a href="#">music</a> & riding his bicycle.


#-------------------------------
# Contact links
twitter: https://twitter.com/ld_manh # Add your Twitter handle
facebook: https://facebook.com/ldm.1011
instagram: https://instagram.com/lleducmanh
telegram: aa
linkedin: https://www.linkedin.com/in/le-duc-manh-16a8b31b1/


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
